-- ============================================================================
--  009 — Overnight Reports (Morning Market Report pipeline)
--
--  Creates:
--    overnight_reports — Stores one immutable report per league per date.
--                        Generated by a daily scheduled job from odds_snapshots.
--                        Read by /api/overnight-report and subscriber dashboard.
--                        Designed for later reuse by social posts & email digests.
--
--  Does NOT modify any existing tables.
-- ============================================================================

CREATE TABLE IF NOT EXISTS overnight_reports (
  id            uuid DEFAULT gen_random_uuid() PRIMARY KEY,

  -- ── Identity ────────────────────────────────────────────────────────────
  league        text        NOT NULL,              -- NBA, NCAAB, NHL, MLB
  report_date   date        NOT NULL,              -- the morning this report covers
  UNIQUE (league, report_date),                    -- one report per league per date

  -- ── Status lifecycle ────────────────────────────────────────────────────
  --   pending           → job started, not yet complete
  --   complete          → report generated and stored
  --   failed            → job errored, see error_message
  --   insufficient_data → not enough odds history to generate
  status        text        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'complete', 'failed', 'insufficient_data')),
  error_message text,                              -- populated on failed status

  -- ── Source window ───────────────────────────────────────────────────────
  --   The UTC time range of odds_snapshots consumed for this report.
  window_start  timestamptz,                       -- e.g. previous day 02:00 UTC
  window_end    timestamptz,                       -- e.g. current day 10:00 UTC
  snapshot_count int        DEFAULT 0,             -- total odds_snapshots rows consumed
  game_count    int         DEFAULT 0,             -- distinct canonical games analyzed

  -- ── Computed stats (structured) ─────────────────────────────────────────
  --   Raw analytical output — used by admin debug view and future consumers.
  --   Schema: { games: GameAnalysis[], aggregate: AggregateStats }
  computed_stats jsonb,

  -- ── Report payload (narrative) ──────────────────────────────────────────
  --   The final subscriber-facing report. Immutable after generation.
  --   Schema: {
  --     headline: string,
  --     quick_stats: QuickStats,
  --     top_signals: TopSignal[],
  --     frozen_line_watch: FrozenLine[],
  --     market_themes: string[],
  --     what_to_watch: WatchItem[],
  --     generated_at: string (ISO)
  --   }
  report_payload jsonb,

  -- ── Timestamps ──────────────────────────────────────────────────────────
  created_at    timestamptz DEFAULT now(),
  updated_at    timestamptz DEFAULT now()
);

-- Auto-update updated_at on row change
CREATE OR REPLACE FUNCTION overnight_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_overnight_reports_updated_at
  BEFORE UPDATE ON overnight_reports
  FOR EACH ROW
  EXECUTE FUNCTION overnight_reports_updated_at();

-- ── Indexes ─────────────────────────────────────────────────────────────────
-- Fast lookup: latest completed report for a league
CREATE INDEX idx_overnight_reports_league_date
  ON overnight_reports (league, report_date DESC);

CREATE INDEX idx_overnight_reports_status
  ON overnight_reports (status);
